version: 3

tasks:
  default:
    cmds:
      - deno fmt src/ functions/ k6/ test/
      - deno lint src/ functions/ k6/ test/ --fix
      - npx tsc
      - yarn run build
      - cd docs && mkdocs build
  server: yarn run local
  build: yarn run build --watch
  test: yarn run test
  prompt: node -e "console.log(JSON.stringify(require('fs').readFileSync('prompt/prompt.md', 'utf8')))"