version: 3

tasks:
  build:
    cmds:
      - deno fmt src/
      - deno lint src/
      - npx tsc
      - yarn run build
      - yarn run test
  default: yarn run local
  watch-build: yarn run build --watch