version: 3

tasks:
  default:
    cmds:
      - deno fmt src/ functions/
      - deno lint src/ functions/
      - npx tsc
      - yarn run build
      - cd docs && mkdocs build
  server: yarn run local
  build: yarn run build --watch
  test: yarn run test