version: 3

tasks:
  default:
    cmds:
      - deno fmt src/ functions/
      - deno lint src/ functions/
      - npx tsc
      - yarn run build
      - yarn run docs:build
  server: yarn run local
  build: yarn run build --watch
  develop: yarn run local