compatibility_date = "2024-04-05"
send_metrics = false

[[kv_namespaces]]
binding = "URL_SHORTENER"
id = "812608f3e6754cdb8ce9e1e36d9320df"

[build]
command = "yarn run build"

[vars]
# API_URL = "http://localhost:8080"
API_URL = "https://knowhere.fly.dev:443"

[env.production.vars]
API_URL = "https://knowhere.fly.dev:443"
