on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: yarn install
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Task
        run: task build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 945954ae6af55e6e4af004fb7772fdc5
          projectName: knowhere-live
          directory: dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
