on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
      - run: yarn install
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: cd docs && pip install -r requirements.txt
      - name: Task
        run: task
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 945954ae6af55e6e4af004fb7772fdc5
          command: pages deploy --project-name=knowhere-live --env=production dist/
